import "../src/styles/globals.css"
const withMT = require("@material-tailwind/react/utils/withMT");



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head/>
      <body>
        <div className="">
        {children}
        </div>
      </body>
    </html>
  )
}
